fl-cfr-test:
  input:
    data: "data.csv"
    sep: ","
  output:
    train: "train.csv"
    test: "test.csv"
    split_dir: "data"
  cross_validation:
    n_splits: 10
    shuffle: true
    stratify: false
    random_state: 42

fc_random_forest:
  input:
    train: "train.csv"
    test: "test.csv"
  output:
    pred: "pred.csv"
    proba: "proba.csv"
    test: "test.csv"
  format:
    sep: ","
    label: "health_status"
  split:
    mode: directory # directory if cross validation was used before, else file
    dir: data # data if cross validation app was used before, else .
  estimators: 100 # number of trees in the forest
  mode: classification # classification or regression
  random_state: 42 # random state for reproducibility
